# Site settings
title: OpenStreetMap Colombia
intro: Ayuda a las comunidades Way√∫u
header-img: img/watercolor_guajira.png
email: info@openstreetmap.co
description: "Bienvenidos al sitio de la OSM Colombia, creando mapas para emergencias."
button: '<br><br><a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>'
baseurl: ""
url: "http://blog.openstreetmap.co"
twitter_username: OpenStreetMapCO
github_username:  OpenStreetMapColombia
facebook_username:  groups/98009745459

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate, jekyll-gallery-generator]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-71933255-1'


gallery:
  # path to the gallery
  dir: galeria
  # title for gallery index
  title: "Galeria"
  # title prefix for gallery page. title=title_prefix+gallery_name
  title_prefix: "Fotos OpenStreetMap Colombia"
  # field to control sorting of galleries for the index page
  # (possible values are: title, date_time, best_image)
  sort_field: "date_time"
  # sizes for thumbnails
  thumbnail_size:
    x: 400
    y: 400
  # custom configuration for individual gallery
  # best_image is image for the index page (defaults to last image)
  # galleries:
  #   chile_trip:
  #     best_image: IMG_1068.JPG
  #   japan_trip:
  #     best_image: IMG_0690.JPG
  #   best:
  #     best_image: snaileo_gonzales.jpg